import { StyleSheet } from 'react-native';
import colors from '../colors';

const cardShadow = {
  shadowColor: colors.shadow,
  shadowOpacity: 0.08,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 6 },
  elevation: 3,
};

const styles = StyleSheet.create({
  container: { padding: 16, backgroundColor: colors.background, flexGrow: 1, paddingBottom: 28, gap: 12 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background, padding: 18 },
  loadingText: { marginTop: 10, color: colors.textGray, fontWeight: '700', textAlign: 'center' },
  hero: { backgroundColor: colors.navy, borderRadius: 30, padding: 18, ...cardShadow },
  heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  heroBadge: { backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  heroBadgeText: { color: colors.white, fontWeight: '800', fontSize: 12 },
  heroTitle: { color: colors.white, fontWeight: '900', fontSize: 28, marginBottom: 6 },
  heroSubtitle: { color: '#DCEBFF', lineHeight: 20, fontWeight: '600' },
  heroHighlight: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 18, backgroundColor: 'rgba(255,255,255,0.10)', borderRadius: 22, padding: 14 },
  heroHighlightItem: { flex: 1 },
  heroHighlightValue: { color: colors.white, fontSize: 28, fontWeight: '900' },
  heroHighlightLabel: { color: '#BFDBFE', fontWeight: '700', marginTop: 2 },
  heroDivider: { width: 1, height: 46, backgroundColor: 'rgba(255,255,255,0.25)', marginHorizontal: 10 },
  heroAlert: { marginTop: 12, backgroundColor: 'rgba(239,68,68,0.16)', borderRadius: 14, padding: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.10)' },
  heroAlertText: { color: colors.white, fontWeight: '700', lineHeight: 18 },
  heroActions: { flexDirection: 'row', gap: 8, marginTop: 14 },
  actionButton: { flex: 1, backgroundColor: colors.fordBlue, borderRadius: 14, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  actionButtonSecondary: { backgroundColor: colors.white },
  actionButtonText: { color: colors.white, fontWeight: '800', fontSize: 13 },
  actionButtonTextSecondary: { color: colors.navy },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  metricCard: { width: '48%', borderWidth: 1, borderRadius: 22, padding: 14, backgroundColor: colors.surface, ...cardShadow },
  metricTitle: { color: colors.textGray, fontWeight: '800', fontSize: 12 },
  metricValue: { color: colors.navy, fontWeight: '900', fontSize: 28, marginVertical: 6 },
  metricSubtitle: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  metric_blue: { borderColor: '#CFE0FF', backgroundColor: colors.surface },
  metric_red: { borderColor: '#FFC9CE', backgroundColor: colors.riskRedSoft },
  metric_yellow: { borderColor: '#FDE1A8', backgroundColor: colors.warningSoft },
  metric_purple: { borderColor: '#E9D5FF', backgroundColor: colors.purpleSoft },
  sectionCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 24, padding: 16, ...cardShadow },
  sectionTitle: { fontWeight: '900', color: colors.navy, fontSize: 18, marginBottom: 4 },
  sectionSubtitle: { color: colors.textGray, fontWeight: '600', lineHeight: 18, marginBottom: 12 },
  tabsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tabButton: { flex: 1, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSoft, borderRadius: 999, paddingVertical: 10, alignItems: 'center' },
  tabButtonActive: { backgroundColor: colors.fordBlue, borderColor: colors.fordBlue },
  tabButtonText: { color: colors.fordBlue, fontWeight: '800', fontSize: 12 },
  tabButtonTextActive: { color: colors.white },
  chartCard: { backgroundColor: colors.surfaceSoft, borderRadius: 18, padding: 14, borderWidth: 1, borderColor: colors.borderSoft },
  chartTitle: { fontWeight: '900', color: colors.navy, fontSize: 15, marginBottom: 4 },
  chartSubtitle: { color: colors.textGray, fontWeight: '600', fontSize: 12, lineHeight: 17, marginBottom: 10 },
  chartList: { gap: 8 },
  chartItem: { paddingVertical: 6, paddingHorizontal: 4, borderRadius: 12 },
  chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  chartLabel: { color: colors.textDark, fontWeight: '800', fontSize: 12, flex: 1, marginRight: 8 },
  chartValue: { color: colors.fordBlue, fontWeight: '900', fontSize: 12 },
  chartTrack: { height: 12, backgroundColor: '#E8EEF7', borderRadius: 999, overflow: 'hidden' },
  chartFill: { height: 12, borderRadius: 999 },
  chartCtaBox: { marginTop: 12, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 16, padding: 12 },
  chartCtaTitle: { color: colors.navy, fontWeight: '900', fontSize: 15, marginBottom: 4 },
  chartCtaDescription: { color: '#334155', lineHeight: 19, fontWeight: '600', fontSize: 13 },
  chartCtaButton: { marginTop: 12, backgroundColor: colors.fordBlue, borderRadius: 12, paddingVertical: 11, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  chartCtaButtonText: { color: colors.white, fontWeight: '800', fontSize: 13 },
});

export default styles;
