import { StyleSheet } from 'react-native';
import colors from '../colors';

const cardShadow = {
  shadowColor: colors.shadow,
  shadowOpacity: 0.08,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 8 },
  elevation: 3,
};

const styles = StyleSheet.create({
  container: { flexGrow: 1, padding: 16, backgroundColor: colors.background, gap: 14, paddingBottom: 28 },
  summaryPanel: { backgroundColor: colors.navy, borderRadius: 24, padding: 18, ...cardShadow },
  summaryTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  summaryTitleBlock: { flex: 1 },
  eyebrow: { color: '#9CC5FF', fontWeight: '900', fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.8 },
  title: { color: colors.white, fontSize: 24, fontWeight: '900', marginTop: 4 },
  roleBadge: { backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.24)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  roleBadgeText: { color: colors.white, fontWeight: '900', fontSize: 12 },
  summaryText: { color: '#DCEBFF', fontWeight: '700', lineHeight: 20, marginTop: 12 },
  loadingInline: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16 },
  loadingText: { color: colors.white, fontWeight: '700' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 16 },
  metricTile: { flexBasis: '48%', flexGrow: 1, borderRadius: 16, padding: 12, borderWidth: 1 },
  metricValue: { color: colors.white, fontWeight: '900', fontSize: 22 },
  metricLabel: { color: '#EAF2FF', fontWeight: '800', fontSize: 12, marginTop: 2 },
  metric_blue: { backgroundColor: 'rgba(47,128,237,0.28)', borderColor: 'rgba(156,197,255,0.35)' },
  metric_red: { backgroundColor: 'rgba(229,72,77,0.26)', borderColor: 'rgba(255,201,206,0.35)' },
  metric_yellow: { backgroundColor: 'rgba(245,158,11,0.24)', borderColor: 'rgba(253,225,168,0.38)' },
  metric_green: { backgroundColor: 'rgba(22,163,74,0.22)', borderColor: 'rgba(187,247,208,0.35)' },
  sectionHeader: { marginTop: 2 },
  sectionTitle: { color: colors.navy, fontWeight: '900', fontSize: 21 },
  sectionSubtitle: { color: colors.textGray, fontWeight: '700', marginTop: 3 },
  card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 20, padding: 12, gap: 8, ...cardShadow },
  leadRow: { borderRadius: 14, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.surfaceSoft, padding: 12, gap: 9 },
  leadRowHighlighted: { borderColor: '#CFE0FF', backgroundColor: colors.white },
  leadTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  leadInfo: { flex: 1 },
  leadName: { color: colors.navy, fontWeight: '900', fontSize: 15 },
  leadMeta: { color: colors.textGray, fontWeight: '700', fontSize: 12, marginTop: 3 },
  riskPill: { backgroundColor: colors.riskRed, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  riskText: { color: colors.white, fontWeight: '900', fontSize: 12 },
  leadReason: { color: colors.textGray, fontWeight: '700', fontSize: 12, lineHeight: 18 },
  leadCta: { backgroundColor: colors.fordBlue, borderRadius: 12, paddingVertical: 11, alignItems: 'center' },
  leadCtaText: { color: colors.white, fontWeight: '900', fontSize: 13 },
  emptyText: { color: colors.textGray, fontWeight: '700', textAlign: 'center', paddingVertical: 10 },
  areaGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 },
  areaCard: { width: '48%', minHeight: 132, backgroundColor: colors.white, borderRadius: 20, borderWidth: 1, padding: 14, justifyContent: 'space-between', ...cardShadow },
  areaIconBox: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(20,87,217,0.10)' },
  areaIcon: { fontSize: 22 },
  areaTitle: { color: colors.navy, fontWeight: '900', fontSize: 16, marginTop: 8 },
  areaSubtitle: { color: colors.textGray, fontWeight: '700', fontSize: 12, lineHeight: 17, marginTop: 3 },
  area_blue: { borderColor: '#CFE0FF' },
  area_green: { borderColor: '#BBF7D0', backgroundColor: colors.successSoft },
  area_purple: { borderColor: '#E9D5FF', backgroundColor: colors.purpleSoft },
  area_yellow: { borderColor: '#FDE1A8', backgroundColor: colors.warningSoft },
  area_red: { borderColor: '#FFC9CE', backgroundColor: colors.riskRedSoft },
  pressed: { opacity: 0.9, transform: [{ scale: 0.99 }] },
});

export default styles;
