server.port=8080

# Oracle
oracle.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
oracle.datasource.username=username
oracle.datasource.password=senha
oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.url=${oracle.datasource.url}
spring.flyway.user=${oracle.datasource.username}
spring.flyway.password=${oracle.datasource.password}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logs
logging.level.com.ford.fordretain=DEBUG
logging.level.org.springframework.web=INFO