CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    telefone VARCHAR2(512),
    regiao VARCHAR2(50) NOT NULL,
    idade NUMBER NOT NULL,
    canal_compra VARCHAR2(50) NOT NULL,
    forma_pagamento VARCHAR2(50) NOT NULL,
    modelo_veiculo VARCHAR2(50) NOT NULL,
    data_compra DATE NOT NULL,
    historico_marca VARCHAR2(512) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE predicoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    perfil_previsto VARCHAR2(30) NOT NULL,
    prob_fiel NUMBER(5,4) NOT NULL,
    prob_abandono NUMBER(5,4) NOT NULL,
    prob_esquecido NUMBER(5,4) NOT NULL,
    prob_economico NUMBER(5,4) NOT NULL,
    acao_sugerida CLOB,
    score_risco NUMBER NOT NULL,
    data_predicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_predicao_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE INDEX idx_predicoes_perfil ON predicoes (perfil_previsto);
CREATE INDEX idx_predicoes_risco ON predicoes (score_risco);
CREATE INDEX idx_clientes_regiao ON clientes (regiao);
CREATE INDEX idx_clientes_modelo ON clientes (modelo_veiculo);
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'ANALISTA' NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_usuario_role CHECK (role IN ('ADMIN', 'GERENTE', 'ANALISTA')),
    CONSTRAINT ck_usuario_ativo CHECK (ativo IN (0, 1))
);

