CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    telefone VARCHAR2(20),
    regiao VARCHAR2(50) NOT NULL,
    idade NUMBER NOT NULL,
    canal_compra VARCHAR2(50) NOT NULL,
    forma_pagamento VARCHAR2(50) NOT NULL,
    modelo_veiculo VARCHAR2(50) NOT NULL,
    data_compra DATE NOT NULL,
    historico_marca VARCHAR2(20) NOT NULL,
    criado_em TIMESTAMP DEFAULT SYSTIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE predicoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    perfil_previsto VARCHAR2(30) NOT NULL,
    prob_fiel NUMBER(5,4) NOT NULL,
    prob_abandono NUMBER(5,4) NOT NULL,
    prob_esquecido NUMBER(5,4) NOT NULL,
    prob_economico NUMBER(5,4) NOT NULL,
    acao_sugerida CLOB,
    score_risco NUMBER NOT NULL,
    data_predicao TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_predicao_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE INDEX idx_predicoes_perfil ON predicoes (perfil_previsto);
CREATE INDEX idx_predicoes_risco ON predicoes (score_risco);
CREATE INDEX idx_clientes_regiao ON clientes (regiao);
CREATE INDEX idx_clientes_modelo ON clientes (modelo_veiculo);