CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'ANALISTA' NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_usuario_role CHECK (role IN ('ADMIN', 'GERENTE', 'ANALISTA')),
    CONSTRAINT ck_usuario_ativo CHECK (ativo IN (0, 1))
);

-- Bootstrap controlado: credencial inicial armazenada somente como BCrypt.
INSERT INTO usuarios (nome, email, senha_hash, role, ativo)
VALUES ('Administrador Ford', 'admin@ford.com', '$2b$10$UhY5a/ojCNHkvkkdxdDCOOLnBWIzjYfSl8sLRVUa1/l7wfDJ0eVIW', 'ADMIN', 1);
